# Cloud band detection configuration file for North Pacific basin

# Compute the inheritance of each cloud band
run_inheritance_tracking: True

# Start/end date and time
startdate: "20160101.00"
enddate: "20161231.00"

# Domain
domain: "southernhemisphere"
# Note: the southern border matters a lot: Polar regions has lots of cold clouds.
hemisphere: "south"
lon_west: 0
lon_east: 360
lat_north: -10
lat_south: -50

# Input files directory
clouddata_path: '/data/directory/lie/ERA5/'
varname_infilename: 'top_net_thermal_radiation' # filename specific ("varname_year.nc")
# Data specific
# calculate daily average for detection
qd_var: True
# temporal resolution of the input data
datatimeresolution: 3.0 # [hour]
# interval of detection in hours of wished period: 24h, 12h, 6h, 3h or 1h
period_detection: 24.
# needs conversion to W.m-2
olr_convert2wm2: True
# variable names in the input data
varname: 'ttr'
timecoord_name: 'time'
xcoord_name: 'longitude'
ycoord_name: 'latitude'

select_djfm: False

# Parameters file for cloud band detection
parameters_file: './parameters/parameters_southhemisphere.yml'

# Save cloud bands, dates with cloud bands (in numpy or pickle formats)
saved_dirpath: './cloud_band_files' # directory where files will be saved
save_dailyvar: False # save daily mean of te variable
save_listdates: False # time range of experiment with dt=1 day
save_listcloudbands: False # list containing lists of cloud band (1 list per day)

# Make figures
dir_figures: './cloud_band_figures'

fig_detection_process: False
fig_time_evolution_object: False
fig_time_evolution_var_cloudband: False
fig_overlay_cloudband: False
fig_show_bbox_around_blobs: False
fig_inheritance_tracking: False
fig_density: False